language: objective-c
podfile: Podfile


before_script:
  - chmod +x travis/before_script.sh
  - chmod +x travis/script.sh
  - chmod +x travis/add-key.sh
  - travis/before_script.sh
  - travis/add-key.sh
script: travis/script.sh
